# Generated by Django 2.2.16 on 2020-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='characterClass',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
