# Generated by Django 2.2.16 on 2020-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pvpgn_user',
        ),
    ]
