# Generated by Django 2.2.16 on 2020-09-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_pvpgn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pvpgn_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customUser', to='authentication.PvpgnBnet', verbose_name='Пользователь PvPGN'),
            preserve_default=False,
        ),
    ]
