# Generated by Django 2.2.16 on 2020-09-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_pvpgn_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvpgnbnet',
            options={},
        ),
    ]
