# Generated by Django 2.2.16 on 2020-09-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200920_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pvpgnbnet',
            options={'managed': False},
        ),
    ]
