# Generated by Django 2.2.16 on 2020-10-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200920_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='blankAvatar.png', upload_to='Avatars', verbose_name='Аватар пользователя'),
        ),
    ]
