# Generated by Django 2.2.16 on 2020-10-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='Avatars/blankAvatar.png', upload_to='Avatars', verbose_name='Аватар пользователя'),
        ),
    ]
