# Generated by Django 2.2.16 on 2020-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20201028_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='Avatars/blankAvatar/blankAvatar.png', upload_to='Avatars', verbose_name='Аватар пользователя'),
        ),
    ]
