# Generated by Django 2.2.16 on 2020-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201101_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='server',
            field=models.CharField(default='MyServer', max_length=100),
            preserve_default=False,
        ),
    ]
