# Generated by Django 2.2.16 on 2020-10-27 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
#        ('authentication', '0012_remove_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержимое сообщения')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата отправления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Было ли прочитано сообщение')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser', verbose_name='Человек в чате')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Message', verbose_name='Человек в чате')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.CustomUser', verbose_name='Человек в чате')),
            ],
        ),
    ]
