# Generated by Django 2.2.16 on 2020-10-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Author',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
