# Generated by Django 2.2.16 on 2020-10-28 05:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_auto_20201028_0855'),
        ('dialogues', '0002_auto_20201027_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='authentication.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Содержимое сообщения')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата отправления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Было ли прочитано сообщение')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomUser', verbose_name='Автор сообщения')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogues.Dialogue', verbose_name='Ссылка на диалог')),
            ],
        ),
    ]
