# Generated by Django 2.2.16 on 2020-10-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0003_dialogue_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
    ]
