# Generated by Django 2.2.16 on 2020-11-01 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0004_auto_20201028_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата отправления'),
        ),
    ]
