# Generated by Django 2.2.16 on 2020-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0006_auto_20201101_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления'),
        ),
    ]
